# Generated by Django 3.2.6 on 2021-08-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('endereco', models.TextField()),
                ('descricao', models.TextField()),
                ('horario', models.IntegerField()),
                ('tipo', models.CharField(choices=[('a', 'Entreterimento'), ('b', 'Lazer'), ('c', 'Arte'), ('s', 'Educacao')], max_length=1)),
            ],
        ),
    ]
