# Generated by Django 3.2.6 on 2021-08-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracao',
            name='tipo',
            field=models.CharField(choices=[('e', 'Entreterimento'), ('l', 'Lazer'), ('a', 'Arte'), ('m', 'Musica')], max_length=1),
        ),
    ]
